project_id = "bichfpvapfibrpplrtcr"

[functions.pinterest-auth]
verify_jwt = false

[functions.fetch-pinterest-board]
verify_jwt = true

[functions.weather]
verify_jwt = false

[functions.fetch-url-metadata]
verify_jwt = false

[functions.canvas-ai-suggestions]
verify_jwt = true

[functions.generate-packing-list]
verify_jwt = true